### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by acabal** [kingrpaul/eleanor-h-porter_pollyanna#1]
- Dedication:

    - Since the dedication is one sentence, it should be one `<p>` element with the line separated with `<br/>`

    - Don't use `<strong>` for when you want small caps. `<strong>` means "strong emphasis", like shouted speech. This is not shouted speech. For the dedication, you can give it small caps with `[epub|type~="dedication"]{ font-variant: small-caps; }`

- Figures: Generally we exclude illustrations in books like these. You can remove them. We want the formatting, but not necessarily the illustrations. Sorry I was not more clear on this, I didn't realize there were illustrations in the page scans. Make sure to run `se print-manifest -i` and `se build --check` again.

- Chapters 4 and 31: Use `<em>` instead of `<strong>`

- Chapter 31 and 32: `<strong>` should not be used in these letters. You can style salutations with `[epub|type~="z3998:salutation"]{ font-variant: small-caps; }`. The `.signature` class should also have small caps in the CSS, so `<strong>` is not appropriate in footers either.

- Footer needs styling: `footer{ margin-top: 1em; text-align: right; }`

- Metadata:

    - Missing `dc:source` for the page scans

    - Missing series information; this is part of the Glad books, you can copy and paste the series template from here: https://github.com/standardebooks/l-m-montgomery_anne-of-green-gables Also see https://standardebooks.org/manual/1.0.0/9-metadata#9.9.3

    - Remove space after opening `<p>` tag in long description

    - Spell out numbers in the long description

    - `<meta property="se:name.person.full-name" refines="#author">` needed for the author, to expand her abbreviated middle name

**Comment by kingrpaul** [comment]
Much appreciated, and thanks for the positive comments. I've made these edits, except not yet removing the figures. The style guide seems to account for illustrations of this sort, it is "juvenile fiction", and the figures look nice(?). If they need to come out, I can remove, but if it's option, I'd like to consider leaving them in place. Just let me know. 

Also, pulling out the <strong>s, I got a better understanding of how things are laid out. But, I think one of the <strong>s in Chapter 4 actually referred to a sort of shout and maybe should have stayed? 

Not sure if it is sufficient to leave these notes in Github, so I am also putting it on the google-group.

Thanks.

- Paul

**Comment by acabal** [comment]
Generally we don't include illustrations, so you can remove them please.

I'm busy this weekend but I'll check back in starting Monday. Thanks!

**Comment by kingrpaul** [comment]
Will do -- thanks for the reply.

**Comment by kingrpaul** [comment]
Illustrations removed.
